# Generated by Django 5.1.6 on 2025-03-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('start_time', models.DateTimeField(help_text='Start time of the event.', verbose_name='Start Time')),
                ('end_time', models.DateTimeField(help_text='End time of the event.', verbose_name='End Time')),
                ('location', models.CharField(blank=True, help_text='Location of the event.', max_length=100, verbose_name='Location')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Scheduling',
                'verbose_name_plural': 'Event Scheduling',
            },
        ),
    ]
