# Generated by Django 5.1.6 on 2025-03-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar_Members',
            new_name='Calendar_User',
        ),
    ]
