# Generated by Django 5.1.6 on 2025-03-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='End time of the event. Format: MM/DD/YYYY HH:MM:SS', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of the event. Format: MM/DD/YYYY HH:MM:SS', verbose_name='Start Time'),
        ),
    ]
