# Generated by Django 5.1.6 on 2025-03-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0002_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='event_photos/default.jpg', null=True, upload_to='event_photos', verbose_name='Event Image'),
        ),
    ]
