# Generated by Django 5.1.6 on 2025-03-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0003_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='static/event_photos/default.jpg', null=True, upload_to='static/event_photos', verbose_name='Event Image'),
        ),
    ]
