# Generated by Django 5.1.6 on 2025-03-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0004_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.DeleteModel(
            name='Calendar_User',
        ),
    ]
