# Generated by Django 5.1.6 on 2025-03-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0005_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT/event_photos', verbose_name='Event Image'),
        ),
    ]
