# Generated by Django 5.1.6 on 2025-03-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0006_alter_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
